### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by Hat52** [OpenSource-Journey/Your-Github-Contributions#10]
I have entered my github user name in the field and after hitting the generate button I got this blank page
![image](https://user-images.githubusercontent.com/44437268/220644401-b695842a-8c83-40ba-b87c-5d876623f811.png)

And in console log I have got this error.

![image](https://user-images.githubusercontent.com/44437268/220644259-98a1c6b1-6d74-42bb-8f53-a46e2074d120.png)

**Comment by Sachin-chaurasiya** [comment]
@Hat52 , Would you like to work on this issue?

**Comment by Hat52** [comment]
> @Hat52 , Would you like to work on this issue?

Yes

**Comment by Sachin-chaurasiya** [comment]
> > @Hat52 , Would you like to work on this issue?
> 
> Yes

Assigned to you.

**Comment by Hat52** [comment]
I am getting this error on my local even if I search you user name instead of mine.
![image](https://user-images.githubusercontent.com/44437268/221598929-d53a41b9-5fa0-4b69-b17c-3f1dbd8bad21.png)

Do I need to configure anything for this to work?

**Comment by Sachin-chaurasiya** [comment]
> I am getting this error on my local even if I search you user name instead of mine. ![image](https://user-images.githubusercontent.com/44437268/221598929-d53a41b9-5fa0-4b69-b17c-3f1dbd8bad21.png)
> 
> Do I need to configure anything for this to work?

Hello @Hat52 , Yes, you can refer to this doc https://github.com/OpenSource-Journey/Your-Github-Contributions#create-env-file-and-add-your-github-access-token
