### ISSUE TITLE
Add error boundary to handle the run time error gracefully

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [OpenSource-Journey/Your-Github-Contributions#13]
Currently, we don't have support for an error boundary to prevent the blank page when something breaks at run time, so need to add the React Error boundary for catching run time errors and show the useful message to the users.

**Comment by ShaileshParmar11** [comment]
I would like to work on this issue!

**Comment by ShaileshParmar11** [comment]
Hi @Sachin-chaurasiya We need to finalize the mock for the fallback component, do you have anything in mind?

**Comment by Sachin-chaurasiya** [comment]
> Hi @Sachin-chaurasiya We need to finalize the mock for the fallback component, do you have anything in mind?

The current design looks good to me, we can improve it in the next iteration, if you have any ideas then feel free to create an issue for the discussion.
