### ISSUE TITLE
Perform data fetch on enter

### ISSUE THREAD

**Issue by Hat52** [OpenSource-Journey/Your-Github-Contributions#21]
Right now when we search the user name, we need to hit the Generate button to be able to get our contribution data. 

What this issue propose is that we should get the use contribution on ENTER as well.

![image](https://user-images.githubusercontent.com/44437268/221828622-baa697ed-fa01-4cf6-90c4-9e3e20a50b38.png)

**Comment by Sachin-chaurasiya** [comment]
@Hat52 , Would you like to work on this issue?

**Comment by Hat52** [comment]
Yes
