### ISSUE TITLE
Change the preview Image on the basis of color theme

### ISSUE THREAD

**Issue by Hat52** [OpenSource-Journey/Your-Github-Contributions#27]
Right now on dashboard we are only showing the dark mode preview,

What this issue propse is that we should display images on the basis of color theme. 
If it is dark then we should display dark theam image and if it is light then we show the light theam image

![image](https://user-images.githubusercontent.com/44437268/222366330-83e7208e-0c7a-420d-80b3-089aa08cc3dd.png)

**Comment by Sachin-chaurasiya** [comment]
@Hat52, Would you like to work on this issue?

**Comment by Hat52** [comment]
Yes

**Comment by Sachin-chaurasiya** [comment]
> Yes

@Hat52 , Assigned to you!

**Comment by Hat52** [comment]
> > Yes
> 
> @Hat52 , Assigned to you!

@Sachin-chaurasiya Can you provide me the image to use for light mode?

**Comment by Sachin-chaurasiya** [comment]
> > > Yes
> > 
> > 
> > @Hat52 , Assigned to you!
> 
> @Sachin-chaurasiya Can you provide me the image to use for light mode?

@Hat52 , Sure I will provide you with the images tomorrow.

**Comment by Hat52** [comment]
> > > > Yes
> > > 
> > > 
> > > @Hat52 , Assigned to you!
> > 
> > 
> > @Sachin-chaurasiya Can you provide me the image to use for light mode?
> 
> @Hat52 , Sure I will provide you with the images tomorrow.

@Sachin-chaurasiya ??

**Comment by Sachin-chaurasiya** [comment]
> > > > > Yes
> > > > 
> > > > 
> > > > @Hat52 , Assigned to you!
> > > 
> > > 
> > > @Sachin-chaurasiya Can you provide me the image to use for light mode?
> > 
> > 
> > @Hat52 , Sure I will provide you with the images tomorrow.
> 
> @Sachin-chaurasiya ??

Hey @Hat52 , was occupied with some other stuff, so will share the image once it's ready.

**Comment by Sachin-chaurasiya** [comment]
@Hat52, Here are the images.
![mockup-1-light](https://user-images.githubusercontent.com/59080942/222948875-c3dc72c1-1f96-42db-b4a5-386b99d0c35c.png)
![mockup-2-light](https://user-images.githubusercontent.com/59080942/222948879-f8e2d643-254b-48f2-8e5d-bbbb8db88767.png)
