### ISSUE TITLE
Link takes to the Github page even if click out side the button 

### ISSUE THREAD

**Issue by Hat52** [OpenSource-Journey/Your-Github-Contributions#30]
If we click outside of the Star on GitHub button, it still takes the user to the GitHub page

![image](https://user-images.githubusercontent.com/44437268/222825083-c77466c9-8eef-4d33-90f0-e8d54fa6749e.png)

What this issue propose is that only when clicking on the button we should take the user to the GitHub page.

**Comment by Hat52** [comment]
Yes

**Comment by Sachin-chaurasiya** [comment]
Hey @Hat52 , when you are creating an issue and if you would like to work on the same then in the description you can mention, 
"I would like to work on this".

Thanks.

**Comment by Hat52** [comment]
> Hey @Hat52 , when you are creating an issue and if you would like to work on the same then in the description you can mention, "I would like to work on this".
> 
> Thanks.

Sure next time I will keep this in mind
