### ISSUE TITLE
[Bug]: Cursor on the card should be default instead of type

### ISSUE THREAD

**Issue by Hat52** [OpenSource-Journey/Your-Github-Contributions#38]
### What happened?

When we hove on the card on the summary page the cursor is changed to type

### Please provide an bug screenshot

https://www.loom.com/share/645a1ad432fe49f7af2e7b3896e98065

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Hat52** [comment]
I would like to work on it.

**Comment by Sachin-chaurasiya** [comment]
> I would like to work on it.

@Hat52 , You already have one issue assigned #37, so you can focus on that one first and come back to this later.

**Comment by Sachin-chaurasiya** [comment]
@Hat52, The description is not clear, can elaborate more?

**Comment by Saikat-Mandal** [comment]
@Hat52 But isn't it suppose to do that only because it is a text ?

**Comment by Hat52** [comment]
> @Hat52 But isn't it suppose to do that only because it is a text ?

Should it not be a default cursor?

**Comment by Jayakumar03** [comment]
I willing work on it.please assign it to me

**Comment by Sachin-chaurasiya** [comment]
> > @Hat52 But isn't it suppose to do that only because it is a text ?
> 
> Should it not be a default cursor?

Hello @Hat52 @Saikat-Mandal , it should be like that only, because it's a text, hence closing this issue.

**Comment by Sachin-chaurasiya** [comment]
> I willing work on it.please assign it to me

@Jayakumar03, this issue has been closed as it is not actually a problem. Please feel free to review other issues.

**Comment by Saikat-Mandal** [comment]
@Sachin-chaurasiya yeh got it.
