### ISSUE TITLE
[Bug]: Button colors are different 

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [OpenSource-Journey/Your-Github-Contributions#43]
### What happened?

On the home page, we have a normal background color for buttons and on the other page, we have a gradient background color, we should have the gradient color for all the buttons.

Steps

- Check out this line in the fallback component https://github.com/OpenSource-Journey/Your-Github-Contributions/blob/main/src/components/ErrorFallback/FallbackComponent.tsx#L24
- Make the changes in this file https://github.com/OpenSource-Journey/Your-Github-Contributions/blob/main/src/components/Forms/UserNamForm.tsx#L54

### Please provide an bug screenshot

- Error page
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/59080942/225428232-7459c10f-e189-477b-ba63-d2457da4778b.png">

- Home Page
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/59080942/225428335-8c3c2239-7ff6-4810-8212-9462aea78afd.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mayukh551** [comment]
I would like to work on this.

**Comment by mayukh551** [comment]
Yup, On it!

**Comment by mayukh551** [comment]
Okay?

![image](https://user-images.githubusercontent.com/82811112/225712244-8b8a4002-e852-4a3c-9b4e-b71cec4fff8a.png)

**Comment by mayukh551** [comment]
ok

**Comment by Sachin-chaurasiya** [comment]
Completed with #45
