### ISSUE TITLE
[Bug]: Copy button is not working on user page

### ISSUE THREAD

**Issue by ShaileshParmar11** [OpenSource-Journey/Your-Github-Contributions#53]
### What happened?

Copy URL button is not working, it should copy the URL path

### Please provide an bug screenshot

https://user-images.githubusercontent.com/71748675/226185468-6ae14ef1-ca21-4c7b-87d6-097b6be29a5a.mp4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zt4ff** [comment]
Hi @Sachin-chaurasiya 
Can you assign this to me, please?

**Comment by JatinSingh08** [comment]
Hey @Sachin-chaurasiya, can yo please assign this issue to me if it's yet not solved ?

**Comment by Sachin-chaurasiya** [comment]
> Hey @Sachin-chaurasiya, can you please assign this issue to me if it's yet not solved ?

Hello @JatinSingh08, Thanks for showing interest, however, this issue is already assigned to @zt4ff and he has open PR for it.
