### ISSUE TITLE
[Feature]: Show stargazerCount and forkCount in popular repository card.

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [OpenSource-Journey/Your-Github-Contributions#54]
### Suggest an idea for this project ?

We have stargazerCount and forkCount available for the popular repository, we should show that in the repository card.

Something like this.

<img width="465" alt="image" src="https://user-images.githubusercontent.com/59080942/226186240-65cacea5-b145-4fe1-a7cc-17c04b5097f3.png">

File reference

https://github.com/OpenSource-Journey/Your-Github-Contributions/blob/main/src/components/GithubPopularRepositories.tsx

### Checklist

I have searched the existing issues to make sure this is not a duplicate, I have checked the documentation and found no answer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mayukh551** [comment]
@Sachin-chaurasiya 
Would love to work on this, if given the chance.

**Comment by Sachin-chaurasiya** [comment]
> @Sachin-chaurasiya Would love to work on this, if given the chance.

@mayukh551 , Assigned to you.

**Comment by mayukh551** [comment]
@Sachin-chaurasiya 
on localhost, when I type my username, no data is shown on the page, i.e. empty

**Comment by Sachin-chaurasiya** [comment]
> @Sachin-chaurasiya on localhost, when I type my username, no data is shown on the page, i.e. empty

@mayukh551 , Make sure to follow this guide for local development.
https://github.com/OpenSource-Journey/Your-Github-Contributions#-how-to-set-up-your-github-contributions-for-development

**Comment by mayukh551** [comment]
Yup. It's working. Thnx for the help

**Comment by mayukh551** [comment]
@Sachin-chaurasiya 

is this okay?

![image](https://user-images.githubusercontent.com/82811112/226532438-1aa50110-1703-42aa-be37-63101fd3c892.png)
