### ISSUE TITLE
[Bug]: Copy URL button should be disable on landing page

### ISSUE THREAD

**Issue by anuj-kumary** [OpenSource-Journey/Your-Github-Contributions#60]
### What happened?
Currently, On landing page Copy Contributions Page URL button is clickable even if input box is empty. 

### Suggestion
On landing page Copy Contributions Page URL button should be disable if input box is empty.

### Please provide an bug screenshot

https://user-images.githubusercontent.com/65344146/227703794-d1c83713-a5e0-4f7d-9ef0-113e8d91cb8a.mov

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bhushansshah** [comment]
Hi, I am new to Open source and came across this issue. Let me know if you need any help. Thanks :)

**Comment by Sachin-chaurasiya** [comment]
> Hi, I am new to Open source and came across this issue. Let me know if you need any help. Thanks :)

Hello @bhushansshah, Would you like to work on this issue?

**Comment by bhushansshah** [comment]
Yes, I would love to. Could you please assign it to me?

**Comment by Sachin-chaurasiya** [comment]
> Yes, I would love to. Could you please assign it to me?

Assigned to you @bhushansshah.
