### ISSUE TITLE
[Bug]: Tooltip should not visible while buttons are disabled

### ISSUE THREAD

**Issue by anuj-kumary** [OpenSource-Journey/Your-Github-Contributions#64]
### What happened?

Even when the buttons are disabled, tooltips are visible while hovering over them.

Hence, when buttons are disabled, the tooltip should be hidden.

### Please provide an bug screenshot

https://user-images.githubusercontent.com/65344146/227759405-2b133d02-4451-403b-9121-d76d7b314e49.mov

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JatinSingh08** [comment]
Hey Anuj, Can you please assign this issue to me? Would love to solve this issue as I've worked on this previously.

**Comment by Sachin-chaurasiya** [comment]
Fixed with #65
