### ISSUE TITLE
[Feature]: Enable settings mode by default

### ISSUE THREAD

**Issue by Petrosdevri** [OpenSource-Journey/Your-Github-Contributions#69]
### Suggest an idea for this project ?

I use dark mode in my browser because it's better for my eyes and websites with dark mode look quite attractive. However, it would be even nicer if a website enabled a mode by default based on the user's mode settings. This is what I think we should do here as well.

My solution would be a CSS selector which looks after the default mode and changes the variable colours to darker shades, as stated on the <code>data-theme</code> selector. It may also require work in the JS selectors to ensure <code>data-theme</code> can be later switched accordingly.

An alternative could be a JS script that changes the mode based on user settings.

### Checklist

I have searched the existing issues to make sure this is not a duplicate

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Sachin-chaurasiya** [comment]
Hello @Petrosdevri , Thanks for opening the issue, I think we can achieve this in Chakra UI itself, Can you explore the documentation of chakra UI?

https://chakra-ui.com/

**Comment by Petrosdevri** [comment]
Hello @Sachin-chaurasiya, I did look into the documentation and found this article: https://chakra-ui.com/docs/styled-system/color-mode. Here are the main notes:

The theme config for color mode has 2 options:

`initialColorMode`: The initial mode you'd like your app to start with when user visit the page for first time (or after storage reset). Can be one of `dark`, `light` or `system`. Default is `light`.

`useSystemColorMode`: If `true`, Chakra UI subscribes to changes in system color mode. If set to `false`, the app's color mode is detached from the `system` color mode. Default is `false`.

```
// theme.js

// 1. import `extendTheme` function
import { extendTheme } from '@chakra-ui/react'

// 2. Add your color mode config
const config = {
  initialColorMode: 'light',
  useSystemColorMode: false,
}

// 3. extend the theme
const theme = extendTheme({ config })

export default theme
```
For typescript, you need to explicitly describe the theme config type as ThemeConfig object.
```
// theme.ts

// 1. import `extendTheme` function
import { extendTheme, type ThemeConfig } from '@chakra-ui/react'

// 2. Add your color mode config
const config: ThemeConfig = {
  initialColorMode: 'light',
  useSystemColorMode: false,
}

// 3. extend the theme
const theme = extendTheme({ config })

export default theme
```
I created a fork to view your projects and wanted to ask whether you have any file for general settings. If not, I would be thinking of adding a `theme.ts` file where I get these settings and then I add it to `index.tsx` to see them in action.

**Comment by Sachin-chaurasiya** [comment]
Hello @Petrosdevri , Go ahead.

**Comment by Sachin-chaurasiya** [comment]
Hello @Petrosdevri , any update on this one?

**Comment by Petrosdevri** [comment]
Hey @Sachin-chaurasiya, I basically left it for some weeks because of some studies I had this period. I will be back on it after up to a week.

**Comment by Petrosdevri** [comment]
Hey @Sachin-chaurasiya I would like to tell you that most of the solutions I have tried based on the documentation fail. I tried to generate my own `theme` function by altering `ColorModeSwitcher.tsx`: 
```
import {
  IconButton,
  IconButtonProps,
  extendTheme,
  useColorMode,
  useColorModeValue,
} from '@chakra-ui/react';
import { FaMoon, FaSun } from 'react-icons/fa';

export const theme = extendTheme({
  config: {
    initialColorMode: 'system',
    useSystsemColorMode: true,
  },
});

type ColorModeSwitcherProps = Omit<IconButtonProps, 'aria-label'>;

export const ColorModeSwitcher: React.FC<ColorModeSwitcherProps> = (props) => {
  const { toggleColorMode } = useColorMode();
  const text = useColorModeValue('dark', 'light');
  const SwitchIcon = useColorModeValue(FaMoon, FaSun);

  return (
    <IconButton
      aria-label={`Switch to ${text} mode`}
      color="current"
      fontSize="lg"
      icon={<SwitchIcon />}
      marginLeft="2"
      size="md"
      variant="ghost"
      onClick={toggleColorMode}
      {...props}
    />
  );
};
```

Then I add it to `App.tsx` by using `ChakraProvider` so the evetual outcome looks like this:  

```
import { Box, ChakraProvider } from '@chakra-ui/react';
import 'App.css';
import AppRoutes from 'AppRoutes';
import theme from 'components/ColorModeSwitcher/ColorMode';
import ErrorFallback from 'components/ErrorFallback/ErrorFallback';
import Footer from 'components/Layout/Footer';
import Header from 'components/Layout/Header';
import ToastMessage from 'components/ToastMessage/ToastMessage';
import { HelmetProvider } from 'react-helmet-async';
import { BrowserRouter as Router } from 'react-router-dom';
import 'react-toastify/dist/ReactToastify.css';

console.log(theme.config);

export const App = () => {
  return (
    <ChakraProvider theme={theme}>
      <HelmetProvider>
        <ToastMessage />
        <Router>
          <ErrorFallback>
            <Header />
            <Box as="main" my={4} p={8} px={{ base: '18', lg: '36' }}>
              <AppRoutes />
            </Box>
            <Footer />
          </ErrorFallback>
        </Router>
      </HelmetProvider>
    </ChakraProvider>
  );
};
```

However it still brings the same error, displaying the website as always white even when using dark mode in the browser.

I wanted to say that I will return back to the issue during the week as I need to work on a few other projects and I already spent some time during these 3 weeks I pledged to return.
