### ISSUE TITLE
Add react-toastify alerts for all the notifications

### ISSUE THREAD

**Issue by anuj-kumary** [OpenSource-Journey/Your-Github-Contributions#9]
Currently, we have normal alerts for the notifications, I would suggest that we should integrate [Toastify](https://www.npmjs.com/package/react-toastify) which help user to differentiate messages between "a success message, warning, error, and so on".
cc: @Sachin-chaurasiya

**Comment by Sachin-chaurasiya** [comment]
@anuj-kumary , Assigned to you.
Happy coding ⭐

**Comment by Jayakumar03** [comment]
I can take it up.

**Comment by anuj-kumary** [comment]
> I can take it up.

Heyy @Jayakumar03 I'm already working on it

**Comment by Sachin-chaurasiya** [comment]
> I can take it up.

Hello @Jayakumar03 , welcome to the community.
There are other good first issues you can check here https://github.com/OpenSource-Journey/Your-Github-Contributions/issues

**Comment by Sachin-chaurasiya** [comment]
Fixed with #11
